# Generated by Django 2.2.10 on 2020-10-16 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('max_retail_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('images', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Categories')),
            ],
        ),
    ]
