# Generated by Django 2.2.10 on 2020-10-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201016_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='selling_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
